name: Launch tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests-back:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22.x']

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./back
      run: npm ci

    - name: Launch unit tests
      working-directory: ./back
      env:
        DATABASE_URL: "file:./pokecenter-test.db"
        JWT_SECRET: "change-me"
      run: npm run test:ci unit


  integration-tests-back:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22.x']

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./back
      run: npm ci


    - name: Launch integration tests
      working-directory: ./back
      env:
        DATABASE_URL: "file:./pokecenter-test.db"
        JWT_SECRET: "ci_secret_123"
      run: |
        npx prisma db push
        npx prisma generate
        npm run test:ci integration
  integration-tests-back:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22.x']

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./back
      run: npm ci

    - name: Launch integration tests
      working-directory: ./back
      run: npm test integration

  functional-tests-front:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22.x']

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Reset database
      working-directory: ./back
      env:
          DATABASE_URL: file:./pokecenter.db
      run: |
        rm -f pokecenter.db
        npm install prisma dotenv
        npx prisma db push
        npx prisma generate
        node ./scripts/seed_db.js

    - name: Launch Backend
      working-directory: ./back
      env:
        DATABASE_URL: file:./pokecenter.db
        JWT_SECRET: secret
        LISTEN_PORT: 3001
      run: node index.js &

    - name: Launch Frontend
      working-directory: ./frontend
      env:
        API_URL: http://localhost:3001
      run: |
        npm run build
        npm run start &

    - name: Wait for front
      run: |
        npx wait-on http://localhost:3000 --timeout 60000

    - name: Run Playwright tests
      working-directory: ./frontend
      env:
        API_URL: http://localhost:3001
        URL_PAGE: http://localhost:3000
      run: |
        npx playwright install --with-deps
        npx playwright test