name: Lauch tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests-back:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22.x']

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./back
      run: npm ci

    - name: Launch unit tests
      working-directory: ./back
      run: npm test


  functional-tests-front:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22.x']

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Reset database
      working-directory: ./back
      env:
          DATABASE_URL: file:./pokecenter.db
      run: |
        rm -f pokecenter.db
        npm install prisma dotenv
        npx prisma db push
        npx prisma generate
        node ./scripts/seed_db.js

    - name: Launch backend
      working-directory: ./back
      env:
        LISTEN_PORT: 3001
        DATABASE_URL: file:./pokecenter.db
        JWT_SECRET: secret
      run: node index.js &

    # - name: Launch frontend
    #   working-directory: ./frontend
    #   env:
    #     API_URL: http://localhost:3001
    #     URL_PAGE: http://localhost:3002
    #   run: |
    #     npm run build
    #     npm run start &

    # - name: Wait for app
    #   run: npx wait-on http://localhost:3002

    # - name: Install Playwright dependencies
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y \
    #       libgtk-4-1 libgraphene-1.0-0 libevent-2.1-7 libopus0 \
    #       libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 \
    #       libwoff2-1 libx264-163 libavif16 libwayland-server0 \
    #       libsecret-1-0 libhyphen0 libharfbuzz-icu0 \
    #       libgstreamer-plugins-base1.0-0 libflite1

    # - name: Lauch functionnal tests
    #   working-directory: ./frontend
    #   env:
    #     API_URL: http://localhost:3001
    #     URL_PAGE: http://localhost:3000
    #   run: |
    #     npx playwright install
    #     npx playwright test

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./frontend
      env:
        API_URL: http://localhost:3001
        URL_PAGE: http://localhost:3000
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30